ALTER TABLE public.announced_products 
ADD COLUMN weight NUMERIC(10,3) DEFAULT 0.5,
ADD COLUMN height NUMERIC(10,2) DEFAULT 10,
ADD COLUMN width NUMERIC(10,2) DEFAULT 15,
ADD COLUMN length NUMERIC(10,2) DEFAULT 15;